### ISSUE TITLE
Some questions about your excellent work

### ISSUE THREAD

**Issue by gjjustc** [Kylin9511/CRNet#1]
I have read the introduction of your work and it is an excellent job. However, I have some questions:
1) I cannot find your paper and can you share your paper.
2) Do you use the same dataset used in CsiNet.  If using the same, have you compared your simulation results with that of the CsiNet+[1] in Table IV?
If you have any problem, please feel free to contact me: jjguo@mail.ustc.edu.cn.

[1] Guo J, Wen C K, Jin S, et al. Convolutional Neural Network based Multiple-Rate Compressive Sensing for Massive MIMO CSI Feedback: Design, Simulation, and Analysis[J]. arXiv preprint arXiv:1906.06007, 2019.

**Comment by Kylin9511** [comment]
Hi~ @gjjustc, thank you very much for your interest in our work.

1. the paper will be submitted to Arxiv soon.
2. I suggest we may leave the issue area for bugs report and have a more detailed discussion via email. I have send you an email from `luzhilin1995@163.com`, you may check it when you are free.
