### ISSUE TITLE
GPU下运行

### ISSUE THREAD

**Issue by yuan-self** [Kylin9511/CRNet#2]
你好请问一下按照你的代码用GPU跑的话，最后跑的时候怎么还是用CPU再运行呀

**Comment by Kylin9511** [comment]
@goudi520  你好，请确认如下事项：
- 你能用pytorch环境正常在GPU上训练其他任务
- 启动脚本中有`--gpu 0`项，且选择的是某个可用的GPU id

这个库就是基于pytorch的基础API的，具体的device代码请参见`CRNet/utils/init.py`中的`init_device`函数，应该问题不大

**Comment by yuan-self** [comment]
好的谢谢你的回复 我再去看一看代码
